import { Senator } from "~/types/senators";

export const SENATOR_LIST: Senator[] = [
  {
    id: 1,
    rapplerProfile: "https://www.rappler.com/people/n12735728-benhur-abalos/",
    name: "Benhur Abalos",
    party: "PFP",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Secretary of the Interior and Local Government (2022–2024)",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Benhur_Abalos",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdG2XqLtANaf7FUmCJZwDxR4o0sL5O12HiAtTu",
    linkName: "BENHUR-ABALOS",
  },
  {
    id: 2,
    name: "Jerome Adonis",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "Secretary general of Kilusang Mayo Uno",
    rapplerProfile: "https://www.rappler.com/people/p75592354-jerome-adonis/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Jerome_Adonis",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTd4D6iskKwxQyTVMiPJfH6ZpXtaKRLBuzdOFNS",
    linkName: "JEROME-ADONIS",
  },
  {
    id: 3,
    name: "Wilson Amad",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p77743701-wilson-amad/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdJg12Ysx3uRZiObl6rDfYQBeIjG4xzhPXdgAU",
    linkName: "WILSON-AMAD",
  },
  {
    id: 4,
    name: "Jocelyn Andamo",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "Secretary general of Filipino Nurses United",
    rapplerProfile: "https://www.rappler.com/people/p44725703-jocelyn-adamo/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Jocelyn_Andamo",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdHHYZPvGmWNjiILu103rh6RJTVt9kovlUKeFn",
    linkName: "JOCELYN-ANDAMO",
  },
  {
    id: 5,
    name: "Bam Aquino",
    party: "KANP",
    coalition: "KiBam",
    notablePosition: "Senator (2013–2019)",
    rapplerProfile: "https://www.rappler.com/people/n26867214-bam-aquino/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Bam_Aquino",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTd1reNkf8EhNCEAYI5WSxsqtuQR3ZUpD9zlLGF",
    linkName: "BAM-AQUINO",
  },
  {
    id: 6,
    name: "Ronnel Arambulo",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "Vice chairperson of Pamalakaya",
    rapplerProfile: "https://www.rappler.com/people/p21504305-ronnel-arambulo/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Ronnel_Arambulo",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdSb3bJz7uaHf0Gtbe4ix5hYIZlJMOzysND2r3",
    linkName: "RONNEL-ARAMBULO",
  },
  {
    id: 7,
    name: "Ernesto Arellano",
    party: "KKK",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p16263797-ernesto-arellano/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdxj04GrRDg4QcX6KowsyhuMVlfN5HpmqtiBbI",
    linkName: "ERNESTO-ARELLANO",
  },
  {
    id: 8,
    name: "Roberto Ballon",
    party: "Independent",
    coalition: "",
    notablePosition: "Leader of Kapunungan sa Gagmay'ng Mangingisda sa Concepcion",
    rapplerProfile: "https://www.rappler.com/people/p12969872-roberto-ballon/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Roberto_Ballon",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdiZqDX3HLdrt5HpECKzAiZhyaGNn3gPv4uJM8",
    linkName: "ROBERTO-BALLON",
  },
  {
    id: 9,
    name: "Abigail Binay",
    party: "NPC",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Mayor of Makati (2016–present)",
    rapplerProfile: "https://rappler.com/people/n56231786-abby-binay",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Abigail_Binay",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdlfcq4szOyUsFuA9MwXtzJWGoHex3TDbgS04n",
    linkName: "ABIGAIL-BINAY",
  },
  {
    id: 10,
    name: "Jimmy Bondoc",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition:
      "Member of the Board of Directors of Philippine Amusement and Gaming Corporation (2021–2022)",
    rapplerProfile: "https://www.rappler.com/people/p64692742-jimmy-bondoc/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Jimmy_Bondoc",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdUQOXddfu5URAdWm1rK9JzkjSC8L4NVY3sX2I",
    linkName: "JIMMY-BONDOC",
  },
  {
    id: 11,
    name: "Bong Revilla",
    party: "Lakas",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
    rapplerProfile: "https://www.rappler.com/people/n34273576-bong-revilla/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Bong_Revilla",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdOf1CBB2fRYThiJNcp6BV5WyP4KD9G12MQkAr",
    linkName: "BONG-REVILLA",
  },
  {
    id: 12,
    name: "Bonifacio Bosita",
    party: "Independent",
    coalition: "Riding-in-tandem Team",
    notablePosition:
      "Incumbent House representative for 1-Rider partylist (2022–present)",
    rapplerProfile: "https://www.rappler.com/people/p82791780-bonifacio-bosita/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Bonifacio_Bosita",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTds7qYtlDENeLFJCQcAUyzP0pbqS2gluxwf6MH",
    linkName: "BONIFACIO-BOSITA",
  },
  {
    id: 13,
    name: "Arlene Brosas",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "Incumbent House representative for GABRIELA (since 2016)",
    rapplerProfile: "https://www.rappler.com/people/p44646012-arlene-brosas/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Arlene_Brosas",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdsc3rGJDENeLFJCQcAUyzP0pbqS2gluxwf6MH",
    linkName: "ARLENE-BROSAS",
  },
  {
    id: 14,
    name: "Roy Cabonegro",
    party: "DPP",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p34326970-roy-cabonegro/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdrIRrI43mfY7KzoCy68GnATv4r2ISaQN3pDiF",
    linkName: "ROY-CABONEGRO",
  },
  {
    id: 15,
    name: "Allen Capuyan",
    party: "PPP",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p13870911-allen-capuyan/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTddlkLRBS0oKxATnL65XcearNH4bVOhm7Wf23v",
    linkName: "ALLEN-CAPUYAN",
  },
  {
    id: 16,
    name: "Teodoro Casiño",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "House representative for Bayan Muna (2004–2013)",
    rapplerProfile: "https://www.rappler.com/people/p78645871-teddy-casino/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Teodoro_Casi%C3%B1o",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTd4EMxLFwxQyTVMiPJfH6ZpXtaKRLBuzdOFNS0",
    linkName: "TEODORO-CASIÑO",
  },
  {
    id: 17,
    name: "France Castro",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "Incumbent House representative for ACT Teachers (since 2016)",
    rapplerProfile: "https://www.rappler.com/people/p00263645-france-castro/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/France_Castro",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdsn0ymmDENeLFJCQcAUyzP0pbqS2gluxwf6MH",
    linkName: "FRANCE-CASTRO",
  },
  {
    id: 18,
    name: "Pia Cayetano",
    party: "Nacionalista",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
    rapplerProfile: "https://www.rappler.com/people/p87395073-pia-cayetano/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Pia_Cayetano",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdOiNx0v2fRYThiJNcp6BV5WyP4KD9G12MQkAr",
    linkName: "PIA-CAYETANO",
  },
  {
    id: 19,
    name: "David d'Angelo",
    party: "Bunyog",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p75398820-david-d-angelo/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/David_D%27Angelo_(activist)",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdE4ZR5SBX3jVQzG94hHf2cJFRuMbDkP5otryx",
    linkName: "DAVID-D'ANGELO",
  },
  {
    id: 20,
    name: "Angelo de Alban",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p27546679-angelo-de-alban/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdd50EGHS0oKxATnL65XcearNH4bVOhm7Wf23v",
    linkName: "ANGELO-DE-ALBAN",
  },
  {
    id: 21,
    name: "Leody de Guzman",
    party: "PLM",
    coalition: "",
    notablePosition: "Chairman of Bukluran ng Manggagawang Pilipino",
    rapplerProfile: "https://rappler.com/people/n30635729-leody-de-guzman",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Leody_de_Guzman",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdNj5Ko6QW8AVCDkdfaRHbSgrJLqPUYlIMQhFG",
    linkName: "LEODY-DE-GUZMAN",
  },
  {
    id: 22,
    name: "Ronald dela Rosa",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Incumbent senator (since 2019)",
    rapplerProfile: "https://rappler.com/people/n34147697-ronald-dela-rosa",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Ronald_dela_Rosa",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTduc8nbhNXdWFmpVyOqAwYR3hx6NI71PMetC8L",
    linkName: "RONALD-DELA-ROSA",
  },
  {
    id: 23,
    name: "Mimi Doringo",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "Secretary general of Kadamay",
    rapplerProfile: "https://www.rappler.com/people/p18828948-mimi-doringo/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Mimi_Doringo",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdDppMWbfvJ6j2ky0KeRWiTIZMmAtOpcbxLC7n",
    linkName: "MIMI-DORINGO",
  },
  {
    id: 24,
    name: "Arnel Escobal",
    party: "PM",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p87298399-arnel-escobal/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdp1Y2SnKWoSGM5ntLC92XxQsFzfTRJdVUi0r7",
    linkName: "ARNEL-ESCOBAL",
  },
  {
    id: 25,
    name: "Luke Espiritu",
    party: "PLM",
    coalition: "",
    notablePosition: "President of Bukluran ng Manggagawang Pilipino",
    rapplerProfile: "https://www.rappler.com/people/p55643788-luke-espiritu/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Luke_Espiritu",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdxZFWgT4RDg4QcX6KowsyhuMVlfN5HpmqtiBb",
    linkName: "LUKE-ESPIRITU",
  },
  {
    id: 26,
    name: "Mody Floranda",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "Chairperson of PISTON",
    rapplerProfile: "https://www.rappler.com/people/p18272308-mody-floranda/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Mody_Floranda",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdIErlXEnVNSxR4hg0YfqQoP6yOFCarv1A5WZ8",
    linkName: "MODY-FLORANDA",
  },
  {
    id: 27,
    name: "Marc Gamboa",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p45832637-marc-gamboa/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdbGcXSSLimazEwcSgFZ0CK4OxUBflpTG21AX3",
    linkName: "MARC-GAMBOA",
  },
  {
    id: 28,
    name: "Bong Go",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Incumbent senator (since 2019)",
    rapplerProfile: "https://rappler.com/people/n98336404-bong-go",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Bong_Go",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTd7IKgxdTX0eNHS4RydfLOA1KYbDpTaik23grF",
    linkName: "BONG-GO",
  },
  {
    id: 29,
    name: "Norberto Gonzales",
    party: "PDSP",
    coalition: "",
    notablePosition: "Secretary of National Defense (2009–2010)",
    rapplerProfile: "https://www.rappler.com/people/n50319899-norberto-gonzales/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Norberto_Gonzales",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdStQe9Ab7uaHf0Gtbe4ix5hYIZlJMOzysND2r",
    linkName: "NORBERTO-GONZALES",
  },
  {
    id: 30,
    name: "Jesus Hinlo Jr.",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Commissioner of the Presidential Anti-Corruption Commission (2022)",
    rapplerProfile: "https://www.rappler.com/people/p41367627-jayvee-hinlo/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Jesus_Hinlo_Jr.",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTd6OYOZcd8lPq8u372seR0JtcOVMTHIFpEAmbB",
    linkName: "JESUS-HINLO-JR",
  },
  {
    id: 31,
    name: "Gregorio Honasan",
    party: "Reform PH",
    coalition: "",
    notablePosition: "Secretary of Information and Communications Technology (2019–2021)",
    rapplerProfile: "https://www.rappler.com/people/p62701759-gringo-honasan/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Gregorio_Honasan",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdfBwQbn6oCRyrVnbl0kiMedHs6fp1EDA3SFq7",
    linkName: "GREGORIO-HONASAN",
  },
  {
    id: 32,
    name: "Relly Jose Jr.",
    party: "KBL",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p40514825-relly-jose-jr/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdgIx3rzhFPWwGYaynKXrMBvqoe5OV6cmjbTgk",
    linkName: "RELLY-JOSE-JR",
  },
  {
    id: 33,
    name: "Panfilo Lacson",
    party: "Independent",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Senator (2016–2022)",
    rapplerProfile: "https://rappler.com/people/n61661752-panfilo-lacson",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Panfilo_Lacson",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTds38sWmDENeLFJCQcAUyzP0pbqS2gluxwf6MH",
    linkName: "PANFILO-LACSON",
  },
  {
    id: 34,
    name: "Raul Lambino",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition:
      "Administrator and Chief Executive Officer of the Cagayan Economic Zone Authority (2017–2022)",
    rapplerProfile: "https://www.rappler.com/people/p80654400-raul-lambino/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Raul_Lambino",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdEcrzfRBX3jVQzG94hHf2cJFRuMbDkP5otryx",
    linkName: "RAUL-LAMBINO",
  },
  {
    id: 35,
    name: "Lito Lapid",
    party: "NPC",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
    rapplerProfile: "https://rappler.com/people/p46987649-lito-lapid",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Lito_Lapid",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdNyJvayQW8AVCDkdfaRHbSgrJLqPUYlIMQhFG",
    linkName: "LITO-LAPID",
  },
  {
    id: 36,
    name: "Wilbert T. Lee (later withdrew)",
    party: "Aksyon",
    coalition: "",
    notablePosition: "Incumbent House representative for AGRI partylist (since 2022)",
    rapplerProfile: "https://rappler.com/people/p43786492-wilbert-lee",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Wilbert_T._Lee",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdsjjajuDENeLFJCQcAUyzP0pbqS2gluxwf6MH",
    linkName: "WILBERT-T-LEE-(LATER-WITHDREW)",
    withdrew: true,
  },
  {
    id: 37,
    name: "Amirah Lidasan",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition:
      "Co-chairperson of Sandugo Movement of Moro and Indigenous Peoples for Self-Determination",
    rapplerProfile: "https://www.rappler.com/people/p58779206-amirah-lidasan/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Amirah_Lidasan",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdxh0jyBRDg4QcX6KowsyhuMVlfN5HpmqtiBbI",
    linkName: "AMIRAH-LIDASAN",
  },
  {
    id: 38,
    name: "Rodante Marcoleta",
    party: "Independent",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Incumbent House representative for SAGIP partylist (since 2016)",
    rapplerProfile: "https://www.rappler.com/people/n91130011-rodante-marcoleta/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Rodante_Marcoleta",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdi0RbqOHLdrt5HpECKzAiZhyaGNn3gPv4uJM8",
    linkName: "RODANTE-MARCOLETA",
  },
  {
    id: 39,
    name: "Imee Marcos",
    party: "Nacionalista",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
    rapplerProfile: "https://rappler.com/people/p69315340-imee-marcos",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Imee_Marcos",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdNq0wU3QW8AVCDkdfaRHbSgrJLqPUYlIMQhFG",
    linkName: "IMEE-MARCOS",
  },
  {
    id: 40,
    name: "Norman Marquez",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://rappler.com/people/p65484824-norman-marquez",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdyke9aHkOPGO6fiCk31W7AT2pr0tghbX9DnSe",
    linkName: "NORMAN-MARQUEZ",
  },
  {
    id: 41,
    name: "Eric Martinez",
    party: "Independent",
    coalition: "",
    notablePosition:
      "Incumbent House representative from Valenzuela's 2nd district (since 2016)",
    rapplerProfile: "https://www.rappler.com/people/p42318706-eric-martinez/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Eric_Martinez",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdUrORESu5URAdWm1rK9JzkjSC8L4NVY3sX2Ip",
    linkName: "ERIC-MARTINEZ",
  },
  {
    id: 42,
    name: "Richard Mata",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p39971197-marites-mata/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Richard_Mata",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdE0rhEfBX3jVQzG94hHf2cJFRuMbDkP5otryx",
    linkName: "RICHARD-MATA",
  },
  {
    id: 43,
    name: "Sonny Matula",
    party: "WPP",
    coalition: "",
    notablePosition: "President of the Federation of Free Workers",
    rapplerProfile: "https://www.rappler.com/people/p11508832-sonny-matula/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Sonny_Matula",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTd5L0BeljZ1OQ8iJYd46jzhA2qmap5PvfnuRMe",
    linkName: "SONNY-MATULA",
  },
  {
    id: 44,
    name: "Liza Maza",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "Lead convenor of National Anti-Poverty Commission (2016–2018)",
    rapplerProfile: "https://www.rappler.com/people/p75976736-liza-maza/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Liza_Maza",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdpXl7zVKWoSGM5ntLC92XxQsFzfTRJdVUi0r7",
    linkName: "LIZA-MAZA",
  },
  {
    id: 45,
    name: "Heidi Mendoza",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p15528438-heidi-mendoza/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Heidi_Mendoza",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdQwrtKCZF0weTdqUBrp6mESaWC4zxYckhLKuM",
    linkName: "HEIDI-MENDOZA",
  },
  {
    id: 46,
    name: "Jose Montemayor Jr.",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p92869356-jose-montemayor/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Jose_Montemayor_Jr.",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdFHM8L04QuoRBmyUY1qigS5VepO6wxdM9fhct",
    linkName: "JOSE-MONTEMAYOR-JR",
  },
  {
    id: 47,
    name: "Subair Mustapha",
    party: "WPP",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p82710540-subair-mustapha/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdFGgzVe4QuoRBmyUY1qigS5VepO6wxdM9fhct",
    linkName: "SUBAIR-MUSTAPHA",
  },
  {
    id: 48,
    name: "Jose Olivar",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p78985059-jose-jessie-olivar/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTd4DEjT6TwxQyTVMiPJfH6ZpXtaKRLBuzdOFNS",
    linkName: "JOSE-OLIVAR",
  },
  {
    id: 49,
    name: "Willie Ong (later withdrew)",
    party: "Aksyon",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/n97241858-willie-ong/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Willie_Ong",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdTxQJSIwtQaUus2ByCFpOlxtjnL180HzTfW79",
    linkName: "WILLIE-ONG-(LATER-WITHDREW)",
    withdrew: true,
  },
  {
    id: 50,
    name: "Manny Pacquiao",
    party: "PFP",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Senator (2016–2022)",
    rapplerProfile: "https://www.rappler.com/people/n63338002-manny-pacquiao/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Manny_Pacquiao",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdDqTHuPfvJ6j2ky0KeRWiTIZMmAtOpcbxLC7n",
    linkName: "MANNY-PACQUIAO",
  },
  {
    id: 51,
    name: "Francis Pangilinan",
    party: "Liberal",
    coalition: "KiBam",
    notablePosition: "Senator (2016–2022)",
    rapplerProfile: "https://rappler.com/people/n19496311-kiko-pangilinan",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Francis_Pangilinan",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdJt7ntXx3uRZiObl6rDfYQBeIjG4xzhPXdgAU",
    linkName: "FRANCIS-PANGILINAN",
  },
  {
    id: 52,
    name: "Ariel Querubin",
    party: "Nacionalista",
    coalition: "Riding-in-tandem Team",
    notablePosition: "Colonel",
    rapplerProfile: "https://www.rappler.com/people/p70563814-ariel-querubin/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Ariel_Querubin",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTd6OEgH0j8lPq8u372seR0JtcOVMTHIFpEAmbB",
    linkName: "ARIEL-QUERUBIN",
  },
  {
    id: 53,
    name: "Apollo Quiboloy",
    party: "Independent",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/n98653484-apollo-quiboloy/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Apollo_Quiboloy",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdFsykEVb4QuoRBmyUY1qigS5VepO6wxdM9fhc",
    linkName: "APOLLO-QUIBOLOY",
  },
  {
    id: 54,
    name: "Danilo Ramos",
    party: "Makabayan",
    coalition: "Oposisyon ng Bayan",
    notablePosition: "Chairperson of Kilusang Magbubukid ng Pilipinas",
    rapplerProfile: "https://www.rappler.com/people/p70813894-danilo-ramos/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Danilo_Ramos",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdcdvV7nd5saWRz5dvEQ2lS7PkLXVYNUOufT8o",
    linkName: "DANILO-RAMOS",
  },
  {
    id: 55,
    name: "Willie Revillame",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p69249448-willie-revillame/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Willie_Revillame",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdx6u2jZRDg4QcX6KowsyhuMVlfN5HpmqtiBbI",
    linkName: "WILLIE-REVILLAME",
  },
  {
    id: 56,
    name: "Vic Rodriguez",
    party: "Independent",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Executive Secretary (2022)",
    rapplerProfile: "https://rappler.com/people/p66508391-vic-rodriguez",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Vic_Rodriguez_(lawyer)",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdtRLWUfEJhRlQ3ZkdoBXq6NVnIrTUEpvSiPFe",
    linkName: "VIC-RODRIGUEZ",
  },
  {
    id: 57,
    name: "Nur-Ana Sahidulla",
    party: "Independent",
    coalition: "",
    notablePosition: "House representative from Sulu's 2nd district (2013–2016)",
    rapplerProfile: "https://www.rappler.com/people/p80570743-nur-ana-sahidulla/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Nur-Ana_Sahidulla",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTduZt08mNXdWFmpVyOqAwYR3hx6NI71PMetC8L",
    linkName: "NUR-ANA-SAHIDULLA",
  },
  {
    id: 58,
    name: "Phillip Salvador",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p74740007-phillip-salvador/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Phillip_Salvador",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdcgks6U5saWRz5dvEQ2lS7PkLXVYNUOufT8op",
    linkName: "PHILLIP-SALVADOR",
  },
  {
    id: 59,
    name: "Tito Sotto",
    party: "NPC",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Senator (2010–2022; Senate president (2018–2022)",
    rapplerProfile: "https://rappler.com/people/n70112766-tito-sotto",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Tito_Sotto",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdmv9PuBUsO24ihFU80WPyzVC5ecaS3uk7MJwl",
    linkName: "TITO-SOTTO",
  },
  {
    id: 60,
    name: "Michael Tapado",
    party: "PM",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p43929736-michael-tapado/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdwf6mmwAsKuxClG4SqpyeQdbzWYnFPAOi80tw",
    linkName: "MICHAEL-TAPADO",
  },
  {
    id: 61,
    name: "Francis Tolentino",
    party: "PFP",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
    rapplerProfile: "https://rappler.com/people/p33309379-francis-tolentino",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Francis_Tolentino",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdFrGdTo4QuoRBmyUY1qigS5VepO6wxdM9fhct",
    linkName: "FRANCIS-TOLENTINO",
  },
  {
    id: 62,
    name: "Ben Tulfo",
    party: "Independent",
    coalition: "",
    notablePosition: "",
    rapplerProfile: "https://www.rappler.com/people/p36706786-ben-tulfo/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Ben_Tulfo",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdi4ZJ5sHLdrt5HpECKzAiZhyaGNn3gPv4uJM8",
    linkName: "BEN-TULFO",
  },
  {
    id: 63,
    name: "Erwin Tulfo",
    party: "Lakas",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent House representative for ACT-CIS partylist (since 2023)",
    rapplerProfile: "https://www.rappler.com/people/p54824881-erwin-tulfo/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Erwin_Tulfo",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdykqhnUqOPGO6fiCk31W7AT2pr0tghbX9DnSe",
    linkName: "ERWIN-TULFO",
  },
  {
    id: 64,
    name: "Mar Valbuena",
    party: "Independent",
    coalition: "",
    notablePosition: "Chairperson of Manibela",
    rapplerProfile: "https://www.rappler.com/people/p18485652-mar-valbuena/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdTmeUWrtQaUus2ByCFpOlxtjnL180HzTfW79Z",
    linkName: "MAR-VALBUENA",
  },
  {
    id: 65,
    name: "Leandro Verceles Jr.",
    party: "Independent",
    coalition: "",
    notablePosition: "Former governor of Catanduanes (2001–2007)",
    rapplerProfile: "https://www.rappler.com/people/p70396374-leandro-verceles/",
    wikipediaProfile: null,
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTdITQIQanVNSxR4hg0YfqQoP6yOFCarv1A5WZ8",
    linkName: "LEANDRO-VERCELES-JR",
  },
  {
    id: 66,
    name: "Camille Villar",
    party: "Nacionalista",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent House representative from Las Piňas (since 2019)",
    rapplerProfile: "https://www.rappler.com/people/p87014514-camille-villar/",
    wikipediaProfile: "https://en.wikipedia.org/wiki/Camille_Villar",
    image: "https://t5zaxa3g5l.ufs.sh/f/QxH0f2F0weTd7FOEzVTX0eNHS4RydfLOA1KYbDpTaik23grF",
    linkName: "CAMILLE-VILLAR",
  },
];
