import { Senators } from "~/types/senators";

export const SENATORS_LIST: Senators[] = [
  {
    id: 1,
    name: "Benhur Abalos",
    party: "PFP",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Secretary of the Interior and Local Government (2022–2024)",
  },
  {
    id: 2,
    name: "Jerome Adonis",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "Secretary general of Kilusang Mayo Uno",
  },
  {
    id: 3,
    name: "Wilson Amad",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 4,
    name: "Jocelyn Andamo",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "Secretary general of Filipino Nurses United",
  },
  {
    id: 5,
    name: "Bam Aquino",
    party: "KANP",
    coalition: "KiBam",
    notablePosition: "Senator (2013–2019)",
  },
  {
    id: 6,
    name: "Ronnel Arambulo",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "Vice chairperson of Pamalakaya",
  },
  {
    id: 7,
    name: "Ernesto Arellano",
    party: "KKK",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 8,
    name: "Roberto Ballon",
    party: "Independent",
    coalition: "",
    notablePosition: "Leader of Kapunungan sa Gagmay'ng Mangingisda sa Concepcion",
  },
  {
    id: 9,
    name: "Abigail Binay",
    party: "NPC",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Mayor of Makati (2016–present)",
  },
  {
    id: 10,
    name: "Jimmy Bondoc",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition:
      "Member of the Board of Directors of Philippine Amusement and Gaming Corporation (2021–2022)",
  },
  {
    id: 11,
    name: "Bong Revilla",
    party: "Lakas",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
  },
  {
    id: 12,
    name: "Bonifacio Bosita",
    party: "Independent",
    coalition: "Riding-in-tandem Team",
    notablePosition:
      "Incumbent House representative for 1-Rider partylist (2022–present)",
  },
  {
    id: 13,
    name: "Arlene Brosas",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "Incumbent House representative for GABRIELA (since 2016)",
  },
  {
    id: 14,
    name: "Roy Cabonegro",
    party: "DPP",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 15,
    name: "Allen Capuyan",
    party: "PPP",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 16,
    name: "Teodoro Casiño",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "House representative for Bayan Muna (2004–2013)",
  },
  {
    id: 17,
    name: "France Castro",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "Incumbent House representative for ACT Teachers (since 2016)",
  },
  {
    id: 18,
    name: "Pia Cayetano",
    party: "Nacionalista",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
  },
  {
    id: 19,
    name: "David d'Angelo",
    party: "Bunyog",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 20,
    name: "Angelo de Alban",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 21,
    name: "Leody de Guzman",
    party: "PLM",
    coalition: "",
    notablePosition: "Chairman of Bukluran ng Manggagawang Pilipino",
  },
  {
    id: 22,
    name: "Ronald dela Rosa",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Incumbent senator (since 2019)",
  },
  {
    id: 23,
    name: "Mimi Doringo",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "Secretary general of Kadamay",
  },
  {
    id: 24,
    name: "Arnel Escobal",
    party: "PM",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 25,
    name: "Luke Espiritu",
    party: "PLM",
    coalition: "",
    notablePosition: "President of Bukluran ng Manggagawang Pilipino",
  },
  {
    id: 26,
    name: "Mody Floranda",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "Chairperson of PISTON",
  },
  {
    id: 27,
    name: "Marc Gamboa",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 28,
    name: "Bong Go",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Incumbent senator (since 2019)",
  },
  {
    id: 29,
    name: "Norberto Gonzales",
    party: "PDSP",
    coalition: "",
    notablePosition: "Secretary of National Defense (2009–2010)",
  },
  {
    id: 30,
    name: "Jesus Hinlo Jr.",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Commissioner of the Presidential Anti-Corruption Commission (2022)",
  },
  {
    id: 31,
    name: "Gregorio Honasan",
    party: "Reform PH",
    coalition: "",
    notablePosition: "Secretary of Information and Communications Technology (2019–2021)",
  },
  {
    id: 32,
    name: "Relly Jose Jr.",
    party: "KBL",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 33,
    name: "Panfilo Lacson",
    party: "Independent",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Senator (2016–2022)",
  },
  {
    id: 34,
    name: "Raul Lambino",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition:
      "Administrator and Chief Executive Officer of the Cagayan Economic Zone Authority (2017–2022)",
  },
  {
    id: 35,
    name: "Lito Lapid",
    party: "NPC",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
  },
  {
    id: 36,
    name: "Wilbert T. Lee (later withdrew)",
    party: "Aksyon",
    coalition: "",
    notablePosition: "Incumbent House representative for AGRI partylist (since 2022)",
  },
  {
    id: 37,
    name: "Amirah Lidasan",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition:
      "Co-chairperson of Sandugo Movement of Moro and Indigenous Peoples for Self-Determination",
  },
  {
    id: 38,
    name: "Rodante Marcoleta",
    party: "Independent",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Incumbent House representative for SAGIP partylist (since 2016)",
  },
  {
    id: 39,
    name: "Imee Marcos",
    party: "Nacionalista",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
  },
  {
    id: 40,
    name: "Norman Marquez",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 41,
    name: "Eric Martinez",
    party: "Independent",
    coalition: "",
    notablePosition:
      "Incumbent House representative from Valenzuela's 2nd district (since 2016)",
  },
  {
    id: 42,
    name: "Richard Mata",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 43,
    name: "Sonny Matula",
    party: "WPP",
    coalition: "",
    notablePosition: "President of the Federation of Free Workers",
  },
  {
    id: 44,
    name: "Liza Maza",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "Lead convenor of National Anti-Poverty Commission (2016–2018)",
  },
  {
    id: 45,
    name: "Heidi Mendoza",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 46,
    name: "Jose Montemayor Jr.",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 47,
    name: "Subair Mustapha",
    party: "WPP",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 48,
    name: "Jose Olivar",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 49,
    name: "Willie Ong (later withdrew)",
    party: "Aksyon",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 50,
    name: "Manny Pacquiao",
    party: "PFP",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Senator (2016–2022)",
  },
  {
    id: 51,
    name: "Francis Pangilinan",
    party: "Liberal",
    coalition: "KiBam",
    notablePosition: "Senator (2016–2022)",
  },
  {
    id: 52,
    name: "Ariel Querubin",
    party: "Nacionalista",
    coalition: "Riding-in-tandem Team",
    notablePosition: "Colonel",
  },
  {
    id: 53,
    name: "Apollo Quiboloy",
    party: "Independent",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "",
  },
  {
    id: 54,
    name: "Danilo Ramos",
    party: "Makabayan",
    coalition: "OnotablePositionisyon ng Bayan",
    notablePosition: "Chairperson of Kilusang Magbubukid ng Pilipinas",
  },
  {
    id: 55,
    name: "Willie Revillame",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 56,
    name: "Vic Rodriguez",
    party: "Independent",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "Executive Secretary (2022)",
  },
  {
    id: 57,
    name: "Nur-Ana Sahidulla",
    party: "Independent",
    coalition: "",
    notablePosition: "House representative from Sulu's 2nd district (2013–2016)",
  },
  {
    id: 58,
    name: "Phillip Salvador",
    party: "PDP",
    coalition: "Partido Demokratiko Pilipino",
    notablePosition: "",
  },
  {
    id: 59,
    name: "Tito Sotto",
    party: "NPC",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Senator (2010–2022; Senate president (2018–2022)",
  },
  {
    id: 60,
    name: "Michael Tapado",
    party: "PM",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 61,
    name: "Francis Tolentino",
    party: "PFP",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent senator (since 2019)",
  },
  {
    id: 62,
    name: "Ben Tulfo",
    party: "Independent",
    coalition: "",
    notablePosition: "",
  },
  {
    id: 63,
    name: "Erwin Tulfo",
    party: "Lakas",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent House representative for ACT-CIS partylist (since 2023)",
  },
  {
    id: 64,
    name: "Mar Valbuena",
    party: "Independent",
    coalition: "",
    notablePosition: "Chairperson of Manibela",
  },
  {
    id: 65,
    name: "Leandro Verceles Jr.",
    party: "Independent",
    coalition: "",
    notablePosition: "Former governor of Catanduanes (2001–2007)",
  },
  {
    id: 66,
    name: "Camille Villar",
    party: "Nacionalista",
    coalition: "Alyansa para sa Bagong Pilipinas",
    notablePosition: "Incumbent House representative from Las Piňas (since 2019)",
  },
];
